stages:
  - sonarqube
  - test
code_check:
  stage: test
  script:
    - export GO111MODULE=on
    - golangci-lint run ./... --fast
    - golint -set_exit_status ./...
  tags:
    - recsys-ci
sonarqube:
  stage: sonarqube
  allow_failure: true
  script:
    # 避免单元测试失败未进行代码扫描
    - sonar-scanner
    - go test ./... -coverprofile ../testCoverage.data -v -cover
    - sonar-scanner
  tags:
    - sonar